apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-d73c
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-d73c@sha256:89159f40e5a415d7a62a8b729a15a7aadfed68367990444a5883eae4e9b1fa17
        name: my-nodejs
        resources: {}
status: {}
